
export const COURSE_QUERY_LIST='COURSE_QUERY_LIST';

export const COURSE_QUERY_BANNER = 'COURSE_QUERY_BANNER';
export const COURSE_QUERY_BANNER3 = 'COURSE_QUERY_BANNER3';

export const COURSE_UNPAY='COURSE_UNPAY';
export const COURSE_HANDLE='COURSE_HANDLE';

